#!/usr/bin/env python3.4
# -*- coding: utf-8 -*-
# @Date    : 2014-04-03 21:12:16
# @Function: youdao dictionary command version
# @Thank for  BeginMan's code in python2
# @Code  : Lewis  2016-11-25 16:53
# python version：Python 3.4.3

import io
import sys
import getopt
import urllib
import urllib.request #if have no this sentence，there will be a error
import simplejson as json


API_KEY = '********'#you can obtain the API_key and KEYFROM from youdao API
KEYFORM = '********'

	
def GetTranslate(txt):
	url = 'http://fanyi.youdao.com/openapi.do'
	data = {
	'keyfrom': KEYFORM,
	'key': API_KEY,
	'type': 'data',
	'doctype': 'json',
	'version': 1.1,
	'q': txt
	}
	data = urllib.parse.urlencode(data)
	url = url+'?'+data
	req = urllib.request.Request(url)
	
	response = urllib.request.urlopen(req)
	result = json.loads(response.read())
	#print(result)
	return result
	
def Sjson(json_data):
	html_pack1= '''<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"><title>Query Result</title></head><body>'''
	html_pack2='''</body></html>'''
	query = json_data.get('query','')				# the querying content
	translation = json_data.get('translation','')
	basic = json_data.get('basic','')				# basic list
	sequence = json_data.get('web',[])
	phonetic,explains_txt,seq_txt,log_word_explains = '''''','''''','''''',''''''
	
	if basic:
		phonetic = basic.get('phonetic','')			# phonetic
		explains = basic.get('explains',[])			# more explains to be here
		for obj in explains:
			explains_txt += obj+'''<br/>'''
			log_word_explains += obj+''','''	
	
	if sequence:                            # sequence parse
		for obj in sequence:
			seq_txt += obj['key']+'''<br/>'''
			values = ''''''
			for i in obj['value']:
				values += i+''','''
			seq_txt += values+'''<br/>'''
		
	print_format = '''****************************************<br/>'''
	print_format += '''Word:  %s [%s]<br/>''' %(query,phonetic)	
	print_format += explains_txt
	print_format += '''---------------------------------------<br/>'''+seq_txt
	print_format += '''****************************************<br/>'''
	print (html_pack1+print_format+html_pack2)



def main():
	sys.stdin = io.TextIOWrapper(sys.stdin.buffer,encoding='utf8')
	sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf8')
	#print(sys.argv[1])
	txt =sys.argv[1]
	if txt:
		Sjson(GetTranslate(txt))

if __name__ == '__main__':
	main()
